# 基本はgithub.com　のレポジトリを指定するだけ
[[plugins]]
repo	= 'Shougo/dein.vim'
repo	= 'Shougo/unite.vim'
repo	= 'Shougo/neocomplete.vim'
repo	= 'scrooloose/nerdtree'
repo	= 'nathanaelkane/vim-indent-guides'

# git clone　後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo	= 'Shougo/vimproc.vim'

	[plugins.build]
	windows	= 'tools\\update-dll-mingw'
	cygwin	= 'make -f make_cygwin.mak'
	mac	= 'make -f make_mac.mak'
	linux	= 'make'
	unix	= 'gmake'


# ブランチやタグを指定したいとき
[[plugins]]
repo	= 'delphinus35/typescript-vim'
rev	= 'colorize-template-strings'

# 特定の条件で読み込みたいとき
#[[plugins]]
#repo	= 'elzr-vim-json'
#if	= '''! has('kaoriya')'''

# 依存関係を指定したいとき
#[[plugins]]
#repo	= 'vim-airline/vim-airline'
#depends	= ['vim-airline-themes']
#
## 依存関係と指定したからと言って、自動でインストールされない
#[[plugins]]
#repo	= 'vim-airline/vim-airline-themes'
[[plugins]]
repo	= 'nanotech/jellybeans.vim'

